version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql-scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: mydb
      FLASK_ENV: development

volumes:
  db_data:
